#ifndef PL0_H
#define PL0_H

// Use the lexer code generated by flex and pl0-vector.l to return a vector of
// token structs containing all of the tokens in the given string of PL/0
// source code.
struct vector *readPL0Tokens(char *source);

// Takes a vector of tokens representing PL/0 source code tokens and returns a
// parse tree representing the structure of the code.
struct parseTree parsePL0Tokens(struct vector *tokens);

#endif
